const express = require('express');
const ctrl = require('./discipline.controller');
const { authenticate, authorize } = require('../../middleware/auth');
const { validatePeriodQuery } = require('../../middleware/validate');
const router = express.Router();
router.get('/', authenticate, validatePeriodQuery, ctrl.list);
router.post('/', authenticate, authorize('ADMIN','HR'), ctrl.create);
router.get('/:id', authenticate, ctrl.getOne);
router.patch('/:id', authenticate, authorize('ADMIN','HR'), ctrl.update);
router.delete('/:id', authenticate, authorize('ADMIN','HR'), ctrl.remove);
router.get('/:employeeId/metrics', authenticate, validatePeriodQuery, ctrl.metrics);
module.exports = router;
